### PR TITLE
feat: spam block

### PR DESCRIPTION
**Pull request by KTibow**

### CODE REVIEW

**Comment by MicrocontrollersDev** [comment]
It should be noted that white chat for nons is already a feature in Hytils and we should really decide how to go forward with chat features in hytils/chatting

**Comment by KTibow** [comment]
> It should be noted that white chat for nons is already a feature in Hytils

i have a feeling any custom tweaks chatting (eg graying out spam) makes would cause hytils to do weird stuff

> and we should really decide how to go forward with chat features in hytils/chatting

elaborate

**Comment by MicrocontrollersDev** [comment]
> elaborate

chatting is a chat mod and hytils is a hypixel mod, so where is the line drawn for chat features for hypixel? should they be in chatting or hytils? i believe wyvest was talking about moving all hytils chat features to chatting in the past but nothing was actually done. not something to be addressed in this pr but should probably be looked into soon

**Comment by KTibow** [comment]
so should i also make a pr to remove white nons + spam hider from hytils?
or should i attempt to add smth so chatting says that it can replace those features first?

**Comment by MicrocontrollersDev** [comment]
@Wyvest help how go about this

**Comment by UnderscoreRayless** [comment]
> > elaborate
> 
> chatting is a chat mod and hytils is a hypixel mod, so where is the line drawn for chat features for hypixel? should they be in chatting or hytils? i believe wyvest was talking about moving all hytils chat features to chatting in the past but nothing was actually done. not something to be addressed in this pr but should probably be looked into soon

Personally I think it should be the other way around, I think it's redundant to have features for Hypixel in mods like evergreen and chatting, if someone needs those features they need to also install everything else, granted these are both great mods that should be installed either way, but imo it's better if features for hypixel are kept into one mod altogether

**Comment by UnderscoreRayless** [comment]
> > Personally I think it should be the other way around, I think it's redundant to have features for Hypixel in mods like evergreen and chatting, if someone needs those features they need to also install everything else, granted these are both great mods that should be installed either way, but imo it's better if features for hypixel are kept into one mod altogether
> 
> hytils is in java 🤮

ah i forgot, well that probably complicates things a lot

**Comment by KTibow** [comment]
[PUBLIC STATIC VOID MAIN STRING ARGS](https://www.youtube.com/watch?v=m4-HM_sCvtQ)

**Comment by MicrocontrollersDev** [comment]
I agree that chatting should not contain hypixel specific features, unless chatting branches out and adds features for other servers as well. if chatting adds modules for many different servers I would be fine with it but honestly that seems non straightforward from a user standpoint and more pain for further chatting development

**Comment by KTibow** [comment]
so like how hard would it be to port hytils reborn to kotlin
or at least allow new stuff to be written in it

**Comment by MicrocontrollersDev** [comment]
> so like how hard would it be to port hytils reborn to kotlin
> or at least allow new stuff to be written in it

i would 100% be down to port hytils to kotlin and would love to at some point. i can create a kotlin refactor branch now and start working on it sometime next week (contributions would be accepted tho ;) ). tbh i’m not very well versed in kotlin but i still like kotlin :)

**Review by EthanDevelops — APPROVED** [review]
LGTM, I'll check to see if I can merge. Where is this spamInfo.json file coming from?

**Pull request merged**
